twitter:
  consumer_key: eg0rp2PksSeqr1sixglP3xSc5
  consumer_secret: TSGJsnvzHhfzUgzQn2DaWu7JDrgADVksgW6767bOGxF4MMH27s
  access_token: 3304539949-EXAIKLlSQZvFoltRpMD6mRTXWaqLcnTOGpH8A0q
  access_token_secret: cqLAOgrZbKP3gjotUkbeebRiju93XcRnQ8P3grfISHyub
